version: '3.8'
services:
  sonya-wms-airflow-fixed:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      - sonya-wms-postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://sonya_wms_user:sonya_wms_pwd123@sonya-wms-postgres/sonya_wms_dwh
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: 'supersecretkey123'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'admin'
      _AIRFLOW_WWW_USER_PASSWORD: 'sonya_wms_admin_pwd'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - "18080:8080"
    command: standalone

  sonya-wms-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sonya_wms_user
      POSTGRES_PASSWORD: sonya_wms_pwd123
      POSTGRES_DB: sonya_wms_dwh
    ports:
      - "56432:5432"
    volumes:
      - sonya_wms_postgres_data:/var/lib/postgresql/data

volumes:
  sonya_wms_postgres_data:
